version: "3.8"

services:
  web:
    depends_on:
      - api

    build: ./frontned
    image: horattiul/frontend-image-library
    ports:
      - "5174:5174"

    environment:
      VITE_API_URL: http://api:8001

  api:
    build: ./backend
    image: horattiul/backend-image-library
    ports:
      - "8001:8001"
